name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Tag Name
        id: tag_name
        run: |
          branch_name=$(echo ${{ github.event.ref }} | sed 's|.*/||')
          if [ "$branch_name" == "main" ]; then
            echo "latest"
          else
            echo "$branch_name" | tr '/' '-' | tr '[:upper:]' '[:lower:]'
          fi
        shell: bash
        env:
          TAG_NAME: ${{ steps.tag_name.outputs.stdout }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ env.TAG_NAME }} .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ env.TAG_NAME }}
